# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language:
  - cpp
  - python

sudo: required

python:
  - 2.7
  - 3.4
  - 3.5

# See http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

compiler: g++

before_install:
#  - mkdir gco_source
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt --user
  - pip install pytest>=3.1.3 coverage codecov nose --user

  - make download
  - make all
  - make test_wrapper
  - ls libcgco.*
  - make rm

  - python setup.py build_ext --inplace
#  - python setup.py install

script:
  - ls libcgco.*
#  - ./test_wrapper
  - nosetests pygco.py --exe --with-doctest
  - nosetests test_examples.py --exe --with-doctest
  - pytest --doctest-modules --ignore=setup.py
  - coverage run --source=pygco test_examples.py

after_success:
  - codecov --token=1aef0194-048a-4c59-a0d1-9408b924c493
  - coverage report
